name: gcp
author: outblocks
usage: GCP deploy plugin
description: Deploy whole stack to Google Cloud Platform
run: $OUTBLOCKS_PLUGIN_DIR/gcp_plugin
actions:
  - deploy
  - dns
state_types:
  - gcp
supports:
  - function
  - service
  - static
supported_types:
  - type: postgresql
  - type: storage
