name: gcp
author: outblocks
usage: GCP deploy plugin
description: Deploy whole stack to Google Cloud Platform
cmd:
  default: $OUTBLOCKS_PLUGIN_DIR/gcp_plugin
  windows: $OUTBLOCKS_PLUGIN_DIR/gcp_plugin.exe
actions:
  - deploy
  - lock
  - state
commands:
  dbproxy:
    short: Create a database proxy
    long: Create a local CloudSQL database proxy.
    input:
      - dependency_states
    flags:
      - name: name
        type: string
        usage: Dependency name to proxy
        required: true
      - name: port
        type: integer
        usage: Port to listen at (defaults to 5432 for postgresql, 3306 for mysql)
state_types:
  - gcp
supports:
  - function
  - service
  - static
supported_types:
  - type: postgresql
  - type: mysql
  - type: storage
