name: gcp
author: outblocks
usage: GCP deploy plugin
description: Deploy whole stack to Google Cloud Platform
cmd:
  default: $OUTBLOCKS_PLUGIN_DIR/gcp_plugin
  windows: $OUTBLOCKS_PLUGIN_DIR/gcp_plugin.exe
actions:
  - deploy
  - lock
  - state
commands:
  dbproxy:
    short: Create a database proxy
    long: Create a local CloudSQL database proxy.
    input:
      - dependency_states
    flags:
      - name: name
        short: "n"
        type: string
        usage: Dependency name to proxy
      - name: port
        short: "p"
        type: integer
        usage: Port to listen at (defaults to 5432 for postgresql, 3306 for mysql)
  create-service-account:
    short: Create a service account
    long: Create a GCP service account with access to current project to use e.g. in CI
    flags:
      - name: name
        short: "n"
        type: string
        usage: Name of service account (defaults to 'outblocks-ci')
state_types:
  - gcp
supports:
  - function
  - service
  - static
supported_types:
  - type: postgresql
  - type: mysql
  - type: storage
