name: gcp
author: outblocks
usage: GCP deploy plugin
description: Deploy whole stack to Google Cloud Platform
cmd:
  default: $OUTBLOCKS_PLUGIN_DIR/gcp_plugin
  windows: $OUTBLOCKS_PLUGIN_DIR/gcp_plugin.exe
actions:
  - deploy
  - dns
  - locking
state_types:
  - gcp
supports:
  - function
  - service
  - static
supported_types:
  - type: postgresql
  - type: mysql
  - type: storage
